application: tinywebdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /images
  static_dir: images

- url: .*
  script: main.app



